repos:
  - repo: https://github.com/pycqa/flake8
    rev: '6.1.0'
    hooks:
      - id: flake8

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.11.0
    hooks:
      - id: black
        name: Black
        language_version: python3.11

  - repo: https://github.com/pycqa/isort
    rev: 5.13.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        additional_dependencies:
          - django-cors-headers==4.3.1
          - django-stubs==4.2.7
          - djangorestframework==3.14.0
          - djangorestframework-stubs==3.14.5

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.55.0
    hooks:
      - id: eslint
        args:
          - frontend/**/*.tsx
        additional_dependencies:
          - eslint@8.55.0
          - eslint-config-next@14.0.4
          - eslint-config-prettier@9.1.0
          - eslint-plugin-simple-import-sort@10.0.0
          - typescript@5.3.3
          - '@typescript-eslint/eslint-plugin@6.14.0'
          - '@typescript-eslint/parser@6.14.0'
