name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Run black
        uses: psf/black@stable

      - name: Run isort
        uses: isort/isort-action@v1
        with:
          requirements-files: "backend/requirements/dev.txt"
